DEB [20190426-16:39:02.089] thr=1   paramiko.transport: starting thread (client mode): 0x3e24e10
DEB [20190426-16:39:02.090] thr=2   paramiko.transport: starting thread (client mode): 0x4b7f130
DEB [20190426-16:39:02.090] thr=3   paramiko.transport: starting thread (client mode): 0x4b7f3f0
DEB [20190426-16:39:02.090] thr=4   paramiko.transport: starting thread (client mode): 0x3e24cd0
DEB [20190426-16:39:02.090] thr=5   paramiko.transport: starting thread (client mode): 0x4b7f290
DEB [20190426-16:39:02.090] thr=6   paramiko.transport: starting thread (client mode): 0x4b7f550
DEB [20190426-16:39:02.090] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.2
DEB [20190426-16:39:02.091] thr=3   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.2
DEB [20190426-16:39:02.091] thr=2   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.2
DEB [20190426-16:39:02.091] thr=4   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.2
DEB [20190426-16:39:02.091] thr=5   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.2
DEB [20190426-16:39:02.091] thr=6   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.2
DEB [20190426-16:39:02.104] thr=4   paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_7.4
INF [20190426-16:39:02.104] thr=4   paramiko.transport: Connected (version 2.0, client OpenSSH_7.4)
DEB [20190426-16:39:02.108] thr=4   paramiko.transport: kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEB [20190426-16:39:02.108] thr=4   paramiko.transport: Kex agreed: ecdh-sha2-nistp256
DEB [20190426-16:39:02.108] thr=4   paramiko.transport: HostKey agreed: ssh-ed25519
DEB [20190426-16:39:02.108] thr=4   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20190426-16:39:02.108] thr=4   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20190426-16:39:02.108] thr=4   paramiko.transport: Compression agreed: none
DEB [20190426-16:39:02.112] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_7.9p1 Debian-9
INF [20190426-16:39:02.112] thr=1   paramiko.transport: Connected (version 2.0, client OpenSSH_7.9p1)
DEB [20190426-16:39:02.114] thr=1   paramiko.transport: kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEB [20190426-16:39:02.114] thr=1   paramiko.transport: Kex agreed: ecdh-sha2-nistp256
DEB [20190426-16:39:02.114] thr=1   paramiko.transport: HostKey agreed: ssh-ed25519
DEB [20190426-16:39:02.114] thr=1   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20190426-16:39:02.114] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20190426-16:39:02.115] thr=1   paramiko.transport: Compression agreed: none
DEB [20190426-16:39:02.183] thr=4   paramiko.transport: kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEB [20190426-16:39:02.184] thr=1   paramiko.transport: kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEB [20190426-16:39:02.184] thr=4   paramiko.transport: Switch to new keys ...
DEB [20190426-16:39:02.184] thr=7   paramiko.transport: Adding ssh-ed25519 host key for 10.49.20.152: b'd92fcb1a9255b6eb6daebd0435cf848f'
DEB [20190426-16:39:02.185] thr=1   paramiko.transport: Switch to new keys ...
DEB [20190426-16:39:02.185] thr=8   paramiko.transport: Adding ssh-ed25519 host key for 10.49.20.156: b'110c4253d5eedecae1ba24eafbbe2ba9'
DEB [20190426-16:39:02.225] thr=4   paramiko.transport: userauth is OK
DEB [20190426-16:39:02.229] thr=1   paramiko.transport: userauth is OK
INF [20190426-16:39:02.255] thr=1   paramiko.transport: Authentication (password) successful!
DEB [20190426-16:39:02.256] thr=1   paramiko.transport: EOF in transport thread
INF [20190426-16:39:03.199] thr=4   paramiko.transport: Authentication (password) successful!
DEB [20190426-16:39:03.199] thr=4   paramiko.transport: EOF in transport thread
ERR [20190426-16:39:17.120] thr=5   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20190426-16:39:17.120] thr=2   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20190426-16:39:17.120] thr=3   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20190426-16:39:17.120] thr=6   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20190426-16:39:17.130] thr=3   paramiko.transport: Traceback (most recent call last):
ERR [20190426-16:39:17.131] thr=2   paramiko.transport: Traceback (most recent call last):
ERR [20190426-16:39:17.131] thr=3   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 2138, in _check_banner
ERR [20190426-16:39:17.131] thr=2   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 2138, in _check_banner
ERR [20190426-16:39:17.132] thr=5   paramiko.transport: Traceback (most recent call last):
ERR [20190426-16:39:17.132] thr=3   paramiko.transport:     buf = self.packetizer.readline(timeout)
ERR [20190426-16:39:17.133] thr=6   paramiko.transport: Traceback (most recent call last):
ERR [20190426-16:39:17.133] thr=2   paramiko.transport:     buf = self.packetizer.readline(timeout)
ERR [20190426-16:39:17.133] thr=5   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 2138, in _check_banner
ERR [20190426-16:39:17.133] thr=3   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\packet.py", line 367, in readline
ERR [20190426-16:39:17.134] thr=6   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 2138, in _check_banner
ERR [20190426-16:39:17.134] thr=2   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\packet.py", line 367, in readline
ERR [20190426-16:39:17.134] thr=5   paramiko.transport:     buf = self.packetizer.readline(timeout)
ERR [20190426-16:39:17.134] thr=3   paramiko.transport:     buf += self._read_timeout(timeout)
ERR [20190426-16:39:17.135] thr=6   paramiko.transport:     buf = self.packetizer.readline(timeout)
ERR [20190426-16:39:17.135] thr=2   paramiko.transport:     buf += self._read_timeout(timeout)
ERR [20190426-16:39:17.135] thr=5   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\packet.py", line 367, in readline
ERR [20190426-16:39:17.135] thr=3   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\packet.py", line 576, in _read_timeout
ERR [20190426-16:39:17.136] thr=6   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\packet.py", line 367, in readline
ERR [20190426-16:39:17.136] thr=2   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\packet.py", line 576, in _read_timeout
ERR [20190426-16:39:17.136] thr=5   paramiko.transport:     buf += self._read_timeout(timeout)
ERR [20190426-16:39:17.136] thr=3   paramiko.transport:     raise socket.timeout()
ERR [20190426-16:39:17.136] thr=6   paramiko.transport:     buf += self._read_timeout(timeout)
ERR [20190426-16:39:17.137] thr=2   paramiko.transport:     raise socket.timeout()
ERR [20190426-16:39:17.137] thr=5   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\packet.py", line 576, in _read_timeout
ERR [20190426-16:39:17.137] thr=3   paramiko.transport: socket.timeout
ERR [20190426-16:39:17.137] thr=6   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\packet.py", line 576, in _read_timeout
ERR [20190426-16:39:17.138] thr=2   paramiko.transport: socket.timeout
ERR [20190426-16:39:17.138] thr=5   paramiko.transport:     raise socket.timeout()
ERR [20190426-16:39:17.138] thr=3   paramiko.transport: 
ERR [20190426-16:39:17.138] thr=6   paramiko.transport:     raise socket.timeout()
ERR [20190426-16:39:17.138] thr=2   paramiko.transport: 
ERR [20190426-16:39:17.139] thr=5   paramiko.transport: socket.timeout
ERR [20190426-16:39:17.139] thr=3   paramiko.transport: During handling of the above exception, another exception occurred:
ERR [20190426-16:39:17.139] thr=6   paramiko.transport: socket.timeout
ERR [20190426-16:39:17.139] thr=2   paramiko.transport: During handling of the above exception, another exception occurred:
ERR [20190426-16:39:17.140] thr=5   paramiko.transport: 
ERR [20190426-16:39:17.140] thr=3   paramiko.transport: 
ERR [20190426-16:39:17.140] thr=6   paramiko.transport: 
ERR [20190426-16:39:17.140] thr=2   paramiko.transport: 
ERR [20190426-16:39:17.140] thr=5   paramiko.transport: During handling of the above exception, another exception occurred:
ERR [20190426-16:39:17.141] thr=3   paramiko.transport: Traceback (most recent call last):
ERR [20190426-16:39:17.141] thr=6   paramiko.transport: During handling of the above exception, another exception occurred:
ERR [20190426-16:39:17.141] thr=2   paramiko.transport: Traceback (most recent call last):
ERR [20190426-16:39:17.141] thr=5   paramiko.transport: 
ERR [20190426-16:39:17.141] thr=3   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 1966, in run
ERR [20190426-16:39:17.142] thr=6   paramiko.transport: 
ERR [20190426-16:39:17.142] thr=2   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 1966, in run
ERR [20190426-16:39:17.142] thr=5   paramiko.transport: Traceback (most recent call last):
ERR [20190426-16:39:17.142] thr=3   paramiko.transport:     self._check_banner()
ERR [20190426-16:39:17.143] thr=6   paramiko.transport: Traceback (most recent call last):
ERR [20190426-16:39:17.143] thr=2   paramiko.transport:     self._check_banner()
ERR [20190426-16:39:17.143] thr=5   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 1966, in run
ERR [20190426-16:39:17.143] thr=3   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 2143, in _check_banner
ERR [20190426-16:39:17.143] thr=6   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 1966, in run
ERR [20190426-16:39:17.144] thr=2   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 2143, in _check_banner
ERR [20190426-16:39:17.144] thr=5   paramiko.transport:     self._check_banner()
ERR [20190426-16:39:17.144] thr=3   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20190426-16:39:17.144] thr=6   paramiko.transport:     self._check_banner()
ERR [20190426-16:39:17.145] thr=2   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20190426-16:39:17.145] thr=5   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 2143, in _check_banner
ERR [20190426-16:39:17.145] thr=3   paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERR [20190426-16:39:17.145] thr=6   paramiko.transport:   File "C:\Users\pthumbur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\transport.py", line 2143, in _check_banner
ERR [20190426-16:39:17.145] thr=2   paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERR [20190426-16:39:17.146] thr=5   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20190426-16:39:17.146] thr=3   paramiko.transport: 
ERR [20190426-16:39:17.146] thr=6   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20190426-16:39:17.146] thr=2   paramiko.transport: 
ERR [20190426-16:39:17.147] thr=5   paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERR [20190426-16:39:17.147] thr=6   paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERR [20190426-16:39:17.148] thr=5   paramiko.transport: 
ERR [20190426-16:39:17.148] thr=6   paramiko.transport: 
